import pygame

# Window
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

# Colours
COLOUR_PLAYER = "white"
COLOUR_BACKGROUND = "black" 
COLOUR_ASTEROID = "gray"
COLOUR_SHOT = "yellow"
COLOUR_XP = "cyan"
COLOUR_UI = "white"

# Drawing
LINE_WIDTH = 2
FONT_SIZE = 32

# Player Defaults
PLAYER_RADIUS = 20.0
PLAYER_INITIAL_SPEED = 200.0
PLAYER_INITIAL_DAMAGE = 10
PLAYER_INITIAL_PROJECTILE_COUNT = 1
PLAYER_INITIAL_PROJECTILE_SPEED = 500.0
PLAYER_INITIAL_SHOOT_COOLDOWN= 0.3
PLAYER_INITIAL_XP_MULTIPLIER = 1.0

# Player Limits
PLAYER_MAX_WEAPON_SLOTS = 3
PLAYER_MAX_PASSIVE_SLOTS = 3

# Aiming and Movement
FORWARD_VECTOR = pygame.Vector2(0, 1)
RIGHT_ANGLE_DEGREES = 90.0
SHIP_BASE_WIDTH_RATIO = 1.5

# Inputs
MOUSE_BUTTON_1 = 0

#Shots
SHOT_RADIUS = 5.0
SHOT_LIFETIME = 2.0

#Asteroids
ASTEROID_MIN_RADIUS = 20.0
ASTEROID_KINDS = 3
ASTEROID_INITIAL_SPAWN_RATE = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_SPEED = 40.0
ASTEROID_MAX_SPEED = 100.0

# Progression
INITIAL_PLAYER_LEVEL = 1
INITIAL_PLAYER_XP = 0
INITIAL_XP_REQUIRED = 10
XP_REQUIREMENT_MULTIPLIER = 1.25

# Upgrades
MAX_UPGRADE_LEVEL = 5
LEVEL_UP_CHOICE_COUNT = 3

# Difficulty
DIFFICULTY_START_TIME = 0.0
DIFFICULTY_SPAWN_RATE_DECREASE = 0.01
DIFFICULTY_MIN_SPAWN_RATE = 0.1
DIFFICULTY_SPEED_INCREASE = 2.0