import pygame

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
LINE_WIDTH = 2
COLOUR_PLAYER = "white"
COLOUR_BACKGROUND = "black" 

FORWARD_VECTOR = pygame.Vector2(0, 1)
RIGHT_ANGLE_DEGREES = 90.0
SHIP_BASE_WIDTH_RATIO = 1.5

MOUSE_BUTTON_1 = 0

PLAYER_RADIUS = 20.0
INITIAL_PLAYER_SPEED = 200.0
INITIAL_SHOOT_SPEED = 500.0
INITIAL_SHOOT_COOLDOWN_SECONDS = 0.3

SHOT_RADIUS = 5.0

ASTEROID_MIN_RADIUS = 20.0
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS